<Project Sdk="Dalamud.NET.Sdk/14.0.1">

    <PropertyGroup>
        <Authors>Haplo064</Authors>
        <Version>3.3.2.1</Version>
        <Description>Perfecting Pixels</Description>
        <PackageProjectUrl>https://github.com/Haplo064/PixelPerfect</PackageProjectUrl>
        <RestorePackagesWithLockFile>true</RestorePackagesWithLockFile>
        <AllowUnsafeBlocks>true</AllowUnsafeBlocks>
        <TargetFramework>net10.0-windows7.0</TargetFramework>
    </PropertyGroup>

</Project>
